services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
        - data:/data
    networks:
      - mongodb_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongodb_network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb   # name of the mongo container
      - ME_CONFIG_BASICAUTH=false   # disable basic auth for ease of access via mongo-express (not secure but fine for learning purposes)
    # or you can ssh in container and connect with mongo sh
    # docker exec -it <CONTAINER_ID> /bin/bash
    # mongosh mongodb://rootuser:rootpass@mongodb:27017
    # note you can use the url above to connect also via intellij idea ultimate client
    depends_on:
      - mongodb

volumes:
  data:

networks:
    mongodb_network:
        driver: bridge